### ISSUE TITLE
Support for LuaJIT

### ISSUE THREAD

**Issue by ZhaoXiangXML** [marcopompili/lua-leveldb#11]
Any plan to support LuaJit?

**Comment by marcopompili** [comment]
Not for now, isn't LuaJIT half dead anyway? Mike Pall left the project years ago.

**Comment by ZhaoXiangXML** [comment]
Not dead according to the git commit messages on http://repo.or.cz/w/luajit-2.0.git

**Comment by ZhaoXiangXML** [comment]
And LuaJIT is still actively used in Unity games, so it would be nice to be supported

**Comment by marcopompili** [comment]
Commit https://github.com/marcopompili/lua-leveldb/commit/154ee28e0283e6549f197e1c5363c6686db510d8 could have fixed compatibility issues with LuaJIT, if you want to confirm that.

Thank you
