### ISSUE TITLE
About [byte] type

### ISSUE THREAD

**Issue by fslove** [marcopompili/lua-leveldb#12]
There are support plans?

**Comment by marcopompili** [comment]
You mean storing plain bytes into leveldb? If so yes, I'll restore the old behavior that enables writing directly byte values.

**Comment by fslove** [comment]
Thanks for your reply.
I don't know why, if use Get('key') to check a key exist ,(50~200 connects) CPU 100%.. HDD not is SSD or SAS.
Is this the problem?
https://github.com/google/leveldb/blob/master/doc/index.md#key-layout
https://github.com/google/leveldb/blob/master/doc/index.md#filters

**Comment by fslove** [comment]
How to set info_log and filter_policy ?
Thank your help.

**Comment by marcopompili** [comment]
A `has` method has been introduced for checking the existence of a key: https://github.com/marcopompili/lua-leveldb/pull/9

But it's basically a `get` call without returning the db value (only true or false), kind of a convenience method, if you intend to read a value use `get` directly without using `has`.

Yes it is normal to have multiple connections (100% CPU uncommon). At the moment you can't change filter policies from Lua, not all options are supported, I'll update the source in the next days when I merge the pulls of @KingJaTu with the code I have offline.

**Comment by fslove** [comment]
`static int lvldb_database_check(lua_State *L) {
	DB *db = check_database(L, 1);

	Slice key = lua_to_slice(L, 2);
	string value;

	Status s = db->Get(lvldb_ropt(L, 3), key, &value);

	if (s.ok()) {
		lua_pushboolean(L, true);
	}
	else {
		//cerr << "Error getting value (get): " << s.ToString() << endl;
		lua_pushboolean(L, false);
	}

	return 1;
}
`
yes, i use this _check, cpu 100%  :(

**Comment by fslove** [comment]
My English isn't very good, please don't mind.
`
function get_key(key)
if ldb:check(key) then
http_push_msg("sess.msg","exist")
else
http_push_msg("sess.msg","nil")
end
end



function save_files(key,blod_file)
if not ldb:check(key) then
if ldb:put(key, blod_file)
    then
http_push_msg("sess.msg","OK")
      else
http_push_msg("sess.msg","db save error!")
    end
else
http_push_msg("sess.msg","exist")
end
end


local http_query_key = '01df89bcd7f9b41a6dbb435a2bfb1c2a411d203a' -- a 40 utf8 string form http api
local blod_file = (http_post_body) -- 10Kb~1Mb size binary file form http api post.
local hash = fs.hexdecode(http_query_key) -- hex string to blod (40 -> 20)

save_files(hash,blod_file) -- save file function.

get_key(http_query_key) -- check exist form http api  

-- connects 100~200, in a few hours CPU 100% , i3-3240 (2C 2T),8G Ram.
`

**Comment by KingJaTu** [comment]
The difference between `lvldb_database_get()` and `lvldb_database_has()` is huge to me. Because the nature of the application is to update or insert, doing a `lvldb_database_get()` in many cases will result in a `cerr << "Error getting value (get): " << s.ToString() << endl;` being emitted.

That completely messes up my logs, as it is **NOT** an error. Doing a `has()` first keeps my log noise level down.

**Comment by fslove** [comment]
Sorry, lose your time.
